# Generated by Django 4.2.7 on 2024-10-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0012_booking_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
